def quiz(content, audience, importance, purpose)
  if content=="image" && audience=="family_and_friends" && importance=="1" && purpose=="funny"
      @quiz = "Facebook"
    elsif content=="image" && audience=="family_and_friends" && importance=="1" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="image" && audience=="family_and_friends" && importance=="1" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="image" && audience=="family_and_friends" && importance=="1" && purpose=="event"
      @quiz = "Facebook or/and Snapchat"
    elsif content=="image" && audience=="family_and_friends" && importance=="1" && purpose=="artsy"
      @quiz = "Instagram"
      
    elsif content=="image" && audience=="family_and_friends" && importance=="5" && purpose=="funny"
      @quiz = "Instagram"
    elsif content=="image" && audience=="family_and_friends" && importance=="5" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="image" && audience=="family_and_friends" && importance=="5" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="image" && audience=="family_and_friends" && importance=="5" && purpose=="event"
      @quiz = "Instagram and/or Facebook"
    elsif content=="image" && audience=="family_and_friends" && importance=="5" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="image" && audience=="family_and_friends" && importance=="10" && purpose=="funny"
      @quiz = "Facebook"
    elsif content=="image" && audience=="family_and_friends" && importance=="10" && purpose=="serious"
      @quiz = "Facebook or/and Instagram"
    elsif content=="image" && audience=="family_and_friends" && importance=="10" && purpose=="for_fun"
      @quiz = "Facebook or/and Instagram"
    elsif content=="image" && audience=="family_and_friends" && importance=="10" && purpose=="event"
      @quiz = "Facebook"
    elsif content=="image" && audience=="family_and_friends" && importance=="10" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="image" && audience=="everyone" && importance=="1" && purpose=="funny"
      @quiz = "Facebook"
    elsif content=="image" && audience=="everyone" && importance=="1" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="image" && audience=="everyone" && importance=="1" && purpose=="for_fun"
      @quiz = "Snapchat"
    elsif content=="image" && audience=="everyone" && importance=="1" && purpose=="event"
      @quiz = "Snapchat"
    elsif content=="image" && audience=="everyone" && importance=="1" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="image" && audience=="everyone" && importance=="5" && purpose=="funny"
      @quiz = "Instagram or/and Twitter"
    elsif content=="image" && audience=="everyone" && importance=="5" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="image" && audience=="everyone" && importance=="5" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="image" && audience=="everyone" && importance=="5" && purpose=="event"
      @quiz = "Facebook"
    elsif content=="image" && audience=="everyone" && importance=="5" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="image" && audience=="everyone" && importance=="10" && purpose=="funny"
      @quiz = "Instagram"
    elsif content=="image" && audience=="everyone" && importance=="10" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="image" && audience=="everyone" && importance=="10" && purpose=="for_fun"
      @quiz = "Facebook or/and Instagram"
    elsif content=="image" && audience=="everyone" && importance=="10" && purpose=="event"
      @quiz = "Facebook"
    elsif content=="image" && audience=="everyone" && importance=="10" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="image" && audience=="business" && importance=="1" && purpose=="funny"
      @quiz = "Instagram"
    elsif content=="image" && audience=="business" && importance=="1" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="image" && audience=="business" && importance=="1" && purpose=="for_fun"
      @quiz = "Facebook"
    elsif content=="image" && audience=="business" && importance=="1" && purpose=="event"
      @quiz = "Instagram"
    elsif content=="image" && audience=="business" && importance=="1" && purpose=="artsy"
      @quiz = "Facebook"

    elsif content=="image" && audience=="business" && importance=="5" && purpose=="funny"
      @quiz = "Facebook"
    elsif content=="image" && audience=="business" && importance=="5" && purpose=="serious"
      @quiz = "Facebook or/and Twitter"
    elsif content=="image" && audience=="business" && importance=="5" && purpose=="for_fun"
      @quiz = "Instagram or/and Twitter"
    elsif content=="image" && audience=="business" && importance=="5" && purpose=="event"
      @quiz = "Twitter"
    elsif content=="image" && audience=="business" && importance=="5" && purpose=="artsy"
      @quiz = "Facebook or/and Instagram"
      

    elsif content=="image" && audience=="business" && importance=="10" && purpose=="funny"
      @quiz = "Instagram"
    elsif content=="image" && audience=="business" && importance=="10" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="image" && audience=="business" && importance=="10" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="image" && audience=="business" && importance=="10" && purpose=="event"
      @quiz = "Facebook or/and Twitter"
    elsif content=="image" && audience=="business" && importance=="10" && purpose=="artsy"
      @quiz = "Facebook or/and Instagram"

    elsif content=="text" && audience=="family_and_friends" && importance=="1" && purpose=="funny"
      @quiz = "Twitter"
    elsif content=="text" && audience=="family_and_friends" && importance=="1" && purpose=="serious"
      @quiz = "Twitter or/and Facebook"
    elsif content=="text" && audience=="family_and_friends" && importance=="1" && purpose=="for_fun"
      @quiz = "Facebook"
    elsif content=="text" && audience=="family_and_friends" && importance=="1" && purpose=="event"
      @quiz = "Twitter and/or Snapchat"
    elsif content=="text" && audience=="family_and_friends" && importance=="1" && purpose=="artsy"
      @quiz = "Twitter and/or Snapchat"
      

    elsif content=="text" && audience=="family_and_friends" && importance=="5" && purpose=="funny"
      @quiz = "Facebook or/and Snapchat"
    elsif content=="text" && audience=="family_and_friends" && importance=="5" && purpose=="serious"
      @quiz = "Facebook or/and Twitter"
    elsif content=="text" && audience=="family_and_friends" && importance=="5" && purpose=="for_fun"
      @quiz = "Twitter"
    elsif content=="text" && audience=="family_and_friends" && importance=="5" && purpose=="event"
      @quiz = "Twitter"
    elsif content=="text" && audience=="family_and_friends" && importance=="5" && purpose=="artsy"
      @quiz = "Twitter or/and Instagram"

    elsif content=="text" && audience=="family_and_friends" && importance=="10" && purpose=="funny"
      @quiz = "Twitter"
    elsif content=="text" && audience=="family_and_friends" && importance=="10" && purpose=="serious"
      @quiz = "Facebook or/and Twitter"
    elsif content=="text" && audience=="family_and_friends" && importance=="10" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="text" && audience=="family_and_friends" && importance=="10" && purpose=="event"
      @quiz = "Twitter"
    elsif content=="text" && audience=="family_and_friends" && importance=="10" && purpose=="artsy"
      @quiz = "Twitter or/and Instagram"

    elsif content=="text" && audience=="everyone" && importance=="1" && purpose=="funny"
      @quiz = "Twitter and/or Snapchat"
    elsif content=="text" && audience=="everyone" && importance=="1" && purpose=="serious"
      @quiz = "Facebook or/and Snapchat"
    elsif content=="text" && audience=="everyone" && importance=="1" && purpose=="for_fun"
      @quiz = "Snapchat"
    elsif content=="text" && audience=="everyone" && importance=="1" && purpose=="event"
      @quiz = "Twitter and/or Snapchat"
    elsif content=="text" && audience=="everyone" && importance=="1" && purpose=="artsy"
      @quiz = "Twitter and/or Snapchat"

    elsif content=="text" && audience=="everyone" && importance=="5" && purpose=="funny"
      @quiz = "Twitter"
    elsif content=="text" && audience=="everyone" && importance=="5" && purpose=="serious"
      @quiz = "Twitter or/and Facebook"
    elsif content=="text" && audience=="everyone" && importance=="5" && purpose=="for_fun"
      @quiz = "Instagram or/and Twitter"
    elsif content=="text" && audience=="everyone" && importance=="5" && purpose=="event"
      @quiz = "Twitter"
    elsif content=="text" && audience=="everyone" && importance=="5" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="text" && audience=="everyone" && importance=="10" && purpose=="funny"
      @quiz = "Instagram"
    elsif content=="text" && audience=="everyone" && importance=="10" && purpose=="serious"
      @quiz = "Twitter or/and Facebook"
    elsif content=="text" && audience=="everyone" && importance=="10" && purpose=="for_fun"
      @quiz = "Facebook"
    elsif content=="text" && audience=="everyone" && importance=="10" && purpose=="event"
      @quiz = "Twitter or/and Facebook"
    elsif content=="text" && audience=="everyone" && importance=="10" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="text" && audience=="business" && importance=="1" && purpose=="funny"
      @quiz = "Twitter"
    elsif content=="text" && audience=="business" && importance=="1" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="text" && audience=="business" && importance=="1" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="text" && audience=="business" && importance=="1" && purpose=="event"
      @quiz = "Twitter or/and Facebook"
    elsif content=="text" && audience=="business" && importance=="1" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="text" && audience=="business" && importance=="5" && purpose=="funny"
      @quiz = "Twitter or/and Facebook"
    elsif content=="text" && audience=="business" && importance=="5" && purpose=="serious"
      @quiz = "Twitter"
    elsif content=="text" && audience=="business" && importance=="5" && purpose=="for_fun"
      @quiz = "Facebook"
    elsif content=="text" && audience=="business" && importance=="5" && purpose=="event"
      @quiz = "Instagram or/and Twitter"
    elsif content=="text" && audience=="business" && importance=="5" && purpose=="artsy"
      @quiz = "Instagram or/and Instagram"
      

    elsif content=="text" && audience=="business" && importance=="10" && purpose=="funny"
      @quiz = "Facebook or/and Twitter"
    elsif content=="text" && audience=="business" && importance=="10" && purpose=="serious"
      @quiz = "Twitter"
    elsif content=="text" && audience=="business" && importance=="10" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="text" && audience=="business" && importance=="10" && purpose=="event"
      @quiz = "Twitter"
    elsif content=="text" && audience=="business" && importance=="10" && purpose=="artsy"
      @quiz = "Twitter"

    elsif content=="video" && audience=="family_and_friends" && importance=="1" && purpose=="funny"
      @quiz = "Snapchat or/and Youtube"
    elsif content=="video" && audience=="family_and_friends" && importance=="1" && purpose=="serious"
      @quiz = "Instagram or/and Snapchat"
    elsif content=="video" && audience=="family_and_friends" && importance=="1" && purpose=="for_fun"
      @quiz = "Snapchat"
    elsif content=="video" && audience=="family_and_friends" && importance=="1" && purpose=="event"
      @quiz = "Instagram or/and Snapchat"
    elsif content=="video" && audience=="family_and_friends" && importance=="1" && purpose=="artsy"
      @quiz = "Snapchat or/and Instagram"
      

    elsif content=="video" && audience=="family_and_friends" && importance=="5" && purpose=="funny"
      @quiz = "Instagram or/and Youtube"
    elsif content=="video" && audience=="family_and_friends" && importance=="5" && purpose=="serious"
      @quiz = "Instagram"
    elsif content=="video" && audience=="family_and_friends" && importance=="5" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="video" && audience=="family_and_friends" && importance=="5" && purpose=="event"
      @quiz = "Facebook"
    elsif content=="video" && audience=="family_and_friends" && importance=="5" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="video" && audience=="family_and_friends" && importance=="10" && purpose=="funny"
      @quiz = "Instagram"
    elsif content=="video" && audience=="family_and_friends" && importance=="10" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="video" && audience=="family_and_friends" && importance=="10" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="video" && audience=="family_and_friends" && importance=="10" && purpose=="event"
      @quiz = "Youtube or/and Twitter"
    elsif content=="video" && audience=="family_and_friends" && importance=="10" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="video" && audience=="everyone" && importance=="1" && purpose=="funny"
      @quiz = "Snapchat"
    elsif content=="video" && audience=="everyone" && importance=="1" && purpose=="serious"
      @quiz = "Twitter"
    elsif content=="video" && audience=="everyone" && importance=="1" && purpose=="for_fun"
      @quiz = "Instagram or/and Snapchat"
    elsif content=="video" && audience=="everyone" && importance=="1" && purpose=="event"
      @quiz = "Youtube or/and Snapchat"
    elsif content=="video" && audience=="everyone" && importance=="1" && purpose=="artsy"
      @quiz = "Snapchat"

    elsif content=="video" && audience=="everyone" && importance=="5" && purpose=="funny"
      @quiz = "Instagram"
    elsif content=="video" && audience=="everyone" && importance=="5" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="video" && audience=="everyone" && importance=="5" && purpose=="for_fun"
      @quiz = "Twitter or/and Instagram"
    elsif content=="video" && audience=="everyone" && importance=="5" && purpose=="event"
      @quiz = "Facebook or/and Twitter"
    elsif content=="video" && audience=="everyone" && importance=="5" && purpose=="artsy"
      @quiz = "Snapchat or/and Instagram"

    elsif content=="video" && audience=="everyone" && importance=="10" && purpose=="funny"
      @quiz = "Instagram or/and Youtube"
    elsif content=="video" && audience=="everyone" && importance=="10" && purpose=="serious"
      @quiz = "Twitter or/and Facebook"
    elsif content=="video" && audience=="everyone" && importance=="10" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="video" && audience=="everyone" && importance=="10" && purpose=="event"
      @quiz = "Facebook or/and Instagram"
    elsif content=="video" && audience=="everyone" && importance=="10" && purpose=="artsy"
      @quiz = "Instagram"

    elsif content=="video" && audience=="business" && importance=="1" && purpose=="funny"
      @quiz = "Twitter or/and Youtube"
    elsif content=="video" && audience=="business" && importance=="1" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="video" && audience=="business" && importance=="1" && purpose=="for_fun"
      @quiz = "Facebook"
    elsif content=="video" && audience=="business" && importance=="1" && purpose=="event"
      @quiz = "Instagram"
    elsif content=="video" && audience=="business" && importance=="1" && purpose=="artsy"
      @quiz = "Snapchat or/and Instagram"

    elsif content=="video" && audience=="business" && importance=="5" && purpose=="funny"
      @quiz = "Facebook"
    elsif content=="video" && audience=="business" && importance=="5" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="video" && audience=="business" && importance=="5" && purpose=="for_fun"
      @quiz = "Snapchat"
    elsif content=="video" && audience=="business" && importance=="5" && purpose=="event"
      @quiz = "Instagram or/and Facebook"
    elsif content=="video" && audience=="business" && importance=="5" && purpose=="artsy"
      @quiz = "Instagram"
      

    elsif content=="video" && audience=="business" && importance=="10" && purpose=="funny"
      @quiz = "Instagram"
    elsif content=="video" && audience=="business" && importance=="10" && purpose=="serious"
      @quiz = "Facebook"
    elsif content=="video" && audience=="business" && importance=="10" && purpose=="for_fun"
      @quiz = "Instagram"
    elsif content=="video" && audience=="business" && importance=="10" && purpose=="event"
      @quiz = "Facebook"
    elsif content=="video" && audience=="business" && importance=="10" && purpose=="artsy"
      @quiz = "Instagram"
  end
  @quiz
end
